# Generated by Django 3.2.4 on 2021-06-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evo_id', models.IntegerField(unique=True)),
                ('origin', models.BooleanField(default=True)),
                ('evolution', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('base_stats', models.JSONField(default={})),
                ('evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokedex.evolution')),
            ],
        ),
    ]
